apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:

#kubectl create -f nginx.pod.yml --save-config
#kubectl delete -f nginx.pod.yml
#kubectl desribe pod <pname> -> gives us info on pod